import { Poppins } from "next/font/google";
import "./globals.css";
import AppNav from "./_components/AppNav";
import ProtectRoutes from "./_components/ProtectRoutes";
import { Toaster } from "react-hot-toast";
import QueryProvider from "./_components/providers/QueryProvider";

const poppins = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: ["500","600", "700", "800"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className}  h-full antialiased`}>
      <body className="h-full flex flex-col text-sm bg-[#f0d8a1ab]">
        <QueryProvider>
          <Toaster
            toastOptions={{
              style: { backgroundColor: "#FFF1D3", color: "#8a6b2f" },
            }}
          />
          <ProtectRoutes />
          <AppNav />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
// F0D8A1;