import { Poppins } from "next/font/google";
import "./globals.css";
import AppNav from "./_components/AppNav";

const poppins = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: ["500","600", "700", "800"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className}  h-full antialiased`}
    >
      <body className="h-full flex flex-col text-sm bg-gray-100">
        <AppNav />
        {children}
      </body>
    </html>
  );
}
